/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as LiveRouteImport } from './routes/live'
import { Route as SdVideosRouteImport } from './routes/sd-videos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrajetosRouteImport } from './routes/trajetos'
import { Route as TripsRouteImport } from './routes/trips'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SdVideosRoute = SdVideosRouteImport.update({
  id: '/sd-videos',
  path: '/sd-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrajetosRoute = TrajetosRouteImport.update({
  id: '/trajetos',
  path: '/trajetos',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/alerts': typeof AlertsRoute
  '/live': typeof LiveRoute
  '/sd-videos': typeof SdVideosRoute
  '/settings': typeof SettingsRoute
  '/trajetos': typeof TrajetosRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/alerts': typeof AlertsRoute
  '/live': typeof LiveRoute
  '/sd-videos': typeof SdVideosRoute
  '/settings': typeof SettingsRoute
  '/trajetos': typeof TrajetosRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/alerts': typeof AlertsRoute
  '/live': typeof LiveRoute
  '/sd-videos': typeof SdVideosRoute
  '/settings': typeof SettingsRoute
  '/trajetos': typeof TrajetosRoute
  '/trips': typeof TripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/alerts'
    | '/live'
    | '/sd-videos'
    | '/settings'
    | '/trajetos'
    | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/alerts'
    | '/live'
    | '/sd-videos'
    | '/settings'
    | '/trajetos'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/alerts'
    | '/live'
    | '/sd-videos'
    | '/settings'
    | '/trajetos'
    | '/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AlertsRoute: typeof AlertsRoute
  LiveRoute: typeof LiveRoute
  SdVideosRoute: typeof SdVideosRoute
  SettingsRoute: typeof SettingsRoute
  TrajetosRoute: typeof TrajetosRoute
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sd-videos': {
      id: '/sd-videos'
      path: '/sd-videos'
      fullPath: '/sd-videos'
      preLoaderRoute: typeof SdVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trajetos': {
      id: '/trajetos'
      path: '/trajetos'
      fullPath: '/trajetos'
      preLoaderRoute: typeof TrajetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AlertsRoute: AlertsRoute,
  LiveRoute: LiveRoute,
  SdVideosRoute: SdVideosRoute,
  SettingsRoute: SettingsRoute,
  TrajetosRoute: TrajetosRoute,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
